### PR TITLE
PEP8 Update and Support Achievements

### PR DESCRIPTION
**Pull request by johnwoltman**
I used my text editor to fix the PEP8 "tabs instead of spaces" recommendation.  I added support for achievement counting and listing the achievements.

### CODE REVIEW

**Comment by m0r13** [comment]
Hey, sorry I'm a bit busy at the moment, but I'll have a look at it later.

Another little problem for me is also that I don't have an active Minecraft server anymore. Thus also no up-to-date log files to continue the development of this tool.

**Comment by johnwoltman** [comment]
Since there's no sensitive info that I care about, maybe I can provide a set of logs for testing.  Is there a good website to throw up a bunch gzipped text files?  I could add them to mclogalyzer's repo if that's better.

**Comment by m0r13** [comment]
Providing some log files would be cool. Maybe you would want to replace the ip addresses and/or user names with some random stuff. I think directly adding them to the repo would be okay if they aren't too large.

**Comment by Gjum** [comment]
You could also upload them as [Gist](https://gist.github.com/) instead of gzipping them.

**Comment by m0r13** [comment]
I think it would be better to add them to the repo or upload them somewhere else in an archive, since the log files are already in a specific structure (gzipped log files for every day) which is also needed by mclogalyzer.

**Comment by m0r13** [comment]
Also, I had a short look at your changes and it looks fine. I'll merge it.

**Comment by johnwoltman** [comment]
I will try anonymizing some of my server logs and add them in a future PR.

**Pull request merged**
